service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/aws-java-simple-http-endpoint-0.1-SNAPSHOT.zip

functions:
  currentTime:
    handler: com.stublessapi.learning.serverless.Handler
    events:
      - http:
          path: ping
          method: get
